#!/bin/bash

VENV_DIR=".venv"

if [ ! -d "$VENV_DIR" ]; then
    echo "Creating virtual environment..."
    python3 -m venv $VENV_DIR
    echo "Installing dependencies..."
    ./$VENV_DIR/bin/pip install --upgrade pip
    ./$VENV_DIR/bin/pip install discid musicbrainzngs
fi


if [ -f "main.py" ]; then
    ./$VENV_DIR/bin/python main.py
else
    echo "Error: main.py not found!"
    exit 1
fi
