on:
  release:
    types: [created]

name: Handle Release

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            name: linux-x86_64
          - target: aarch64-unknown-linux-gnu
            name: linux-aarch64
    steps:
      - uses: actions/checkout@v4

      - name: Install cross
        run: cargo install cross
      
      - name: Build
        run: cross build --release --target ${{ matrix.target }}

      - name: Prepare artifact
        run: mv target/${{ matrix.target }}/release/rippy rippy-${{ matrix.name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: rippy-${{ matrix.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
