on:
  release:
    types: [created]

name: Handle Release

jobs:
  build:
    name: Build Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcdio-dev libcdio-cdda-dev libcdio-paranoia-dev 
          sudo apt-get install -y libiso9660-dev libudf-dev

      - name: Build
        run: cargo build --release

      - name: Prepare artifact
        run: mv target/release/rippy rippy-linux-x86_64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: rippy-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
